---
- name: update web, nfs and db servers
  hosts: webservers, nfs, db
  remote_user: araflyayinde
  become: yes
  become_user: root
  tasks:
  - name: ensure wireshark is at the latest version
    yum:
      name: wireshark
      state: latest

- name: update Nginx LB server
  hosts: lb
  remote_user: araflyayinde
  become: yes
  become_user: root
  tasks:
  - name: ensure wireshark is at the latest version
    apt:
      name: wireshark
      state: latest